apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-lab
  labels:
    app: devops-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-lab
  template:
    metadata:
      labels:
        app: devops-lab
    spec:
      containers:
        - name: devops-lab
          image: rik7614/devops-lab:1.0
          ports:
            - containerPort: 5000
